<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1bb5993f0136a3f2a42f4da3e8210884
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'F' => 
        array (
            'Fabiang\\Xmpp\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Fabiang\\Xmpp\\' => 
        array (
            0 => __DIR__ . '/..' . '/fabiang/xmpp/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1bb5993f0136a3f2a42f4da3e8210884::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1bb5993f0136a3f2a42f4da3e8210884::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
