#!/bin/sh

case $1 in
	# Configure this package. If the package must prompt the user for
	# information, do it here.
	configure)
		rm -Rf /var/lib/homegear/node-blue/nodes/variable-in
		rm -Rf /var/lib/homegear/node-blue/nodes/variable-out
		rm -Rf /var/lib/homegear/node-blue/nodes/greater-than
		rm -Rf /var/lib/homegear/node-blue/nodes/link/link-in.hni
		rm -Rf /var/lib/homegear/node-blue/nodes/link/link-out.hni
		rm -Rf /var/lib/homegear/node-blue/nodes/mqtt-broker
		rm -Rf /var/lib/homegear/node-blue/nodes/mqtt-in
		rm -Rf /var/lib/homegear/node-blue/nodes/php-test
		rm -Rf /var/lib/homegear/node-blue/nodes/timer
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/equal*
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/greater-or-equal*
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/greater-than*
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/less-or-equal*
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/less-than*
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/locales/en-US/equal
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/locales/en-US/greater-or-equal
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/locales/en-US/greater-than
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/locales/en-US/less-or-equal
		rm -Rf /var/lib/homegear/node-blue/nodes/basic-logic/locales/en-US/less-than
		rm -Rf /var/lib/homegear/node-blue/nodes/runscript
		rm -Rf /var/lib/homegear/node-blue/nodes/sequence
		sed -i 's/"type":"link-in"/"type":"link in"/g' /data/homegear-data/node-blue/flows.json > /dev/null 2>&1
		sed -i 's/"type":"link-in"/"type":"link in"/g' /var/lib/homegear/node-blue/data/flows.json > /dev/null 2>&1
		sed -i 's/"type":"link-out"/"type":"link out"/g' /data/homegear-data/node-blue/flows.json > /dev/null 2>&1
		sed -i 's/"type":"link-out"/"type":"link out"/g' /var/lib/homegear/node-blue/data/flows.json > /dev/null 2>&1
		chown -R homegear:homegear /var/lib/homegear/node-blue/nodes
		chmod -R 750 /var/lib/homegear/node-blue/nodes
		ln -s node-red-nodes/javascript /var/lib/homegear/node-blue/nodes/javascript
		homegear -e mls > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			homegear -e fr
		fi
		;;

	# Back out of an attempt to upgrade this package FROM THIS VERSION
	# to version $2. Undo the effects of "prerm upgrade $2".
	abort-upgrade)
		;;

	# Back out of an attempt to remove this package, which was due to
	# a conflict with package $3 (version $4). Undo the effects of
	# "prerm remove in-favour $3 $4".
	abort-remove)
		;;

	# Back out of an attempt to deconfigure this package, which was
	# due to package $6 (version $7) which we depend on being removed
	# to make way for package $3 (version $4). Undo the effects of
	# "prerm deconfigure in-favour $3 $4 removing $6 $7".
	abort-deconfigure)
		;;

	*)
		echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;
		;;

esac

#DEBHELPER#
