#!/bin/sh

case $1 in
	# Configure this package. If the package must prompt the user for
	# information, do it here.
	configure)
		rm -Rf /var/lib/homegear/flows/nodes/variable-in
		rm -Rf /var/lib/homegear/flows/nodes/variable-out
		rm -Rf /var/lib/homegear/flows/nodes/greater-than
		rm -Rf /var/lib/homegear/flows/nodes/mqtt-broker
		rm -Rf /var/lib/homegear/flows/nodes/mqtt-in
		rm -Rf /var/lib/homegear/flows/nodes/php-test
		rm -Rf /var/lib/homegear/flows/nodes/timer
		chown -R homegear:homegear /var/lib/homegear/flows/nodes
		chmod -R 550 /var/lib/homegear/flows/nodes
		homegear -e mls > /dev/null 2>&1
		if [ $? -eq 0 ]; then
			homegear -e fr
		fi
		;;

	# Back out of an attempt to upgrade this package FROM THIS VERSION
	# to version $2. Undo the effects of "prerm upgrade $2".
	abort-upgrade)
		;;

	# Back out of an attempt to remove this package, which was due to
	# a conflict with package $3 (version $4). Undo the effects of
	# "prerm remove in-favour $3 $4".
	abort-remove)
		;;

	# Back out of an attempt to deconfigure this package, which was
	# due to package $6 (version $7) which we depend on being removed
	# to make way for package $3 (version $4). Undo the effects of
	# "prerm deconfigure in-favour $3 $4 removing $6 $7".
	abort-deconfigure)
		;;

	*)
		echo "$0: didn't understand being called with \`$1'" 1>&2
		exit 1;
		;;

esac

#DEBHELPER#
